In [ ]:
import pandas as pd

In [ ]:
list1 = [1,2,3,4,5,6]
series1 = pd.Series(list1)
series1

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [ ]:
print(type(list1))
print(type(series1))

<class 'list'>
<class 'pandas.core.series.Series'>

In [ ]:
series2 = pd.Series(list1,index =['a', 'b', 'c','d','e','f'])
series2

a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64

In [ ]:
df = pd.DataFrame({'name':['samira','Haque'], 'age': [20,21]})
df

     name  age
0  samira   20
1   Haque   21

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
iris_df = pd.read_csv('/content/Iris.csv')
iris_df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [ ]:
iris_df.head(5)

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
iris_df.tail(5)

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [ ]:
iris_df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [ ]:
iris_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [ ]:
iris_df.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [ ]:
iris_df[['SepalLengthCm', 'SepalWidthCm']]

     SepalLengthCm  SepalWidthCm
0              5.1           3.5
1              4.9           3.0
2              4.7           3.2
3              4.6           3.1
4              5.0           3.6
..             ...           ...
145            6.7           3.0
146            6.3           2.5
147            6.5           3.0
148            6.2           3.4
149            5.9           3.0

[150 rows x 2 columns]

In [ ]:
x = iris_df[['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']]
y = iris_df['Species']

In [ ]:
x

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0      1            5.1           3.5            1.4           0.2
1      2            4.9           3.0            1.4           0.2
2      3            4.7           3.2            1.3           0.2
3      4            4.6           3.1            1.5           0.2
4      5            5.0           3.6            1.4           0.2
..   ...            ...           ...            ...           ...
145  146            6.7           3.0            5.2           2.3
146  147            6.3           2.5            5.0           1.9
147  148            6.5           3.0            5.2           2.0
148  149            6.2           3.4            5.4           2.3
149  150            5.9           3.0            5.1           1.8

[150 rows x 5 columns]

In [ ]:
y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object

In [ ]:
y.unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [ ]:
type(iris_df['Species'])

pandas.core.series.Series

In [ ]:
data = {
    'name': ['samira', 'haque'],
    'age': [20,21]
}
df = pd.DataFrame(data,index = ['a','b'])
df

     name  age
a  samira   20
b   haque   21

In [ ]:
df.loc["b"]

name    haque
age        21
Name: b, dtype: object

In [ ]:
df.iloc[0]

name    samira
age         20
Name: a, dtype: object

In [ ]:
df.iloc[0][1]

/tmp/ipykernel_8267/2309508539.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][1]

np.int64(20)

In [ ]:
irisdf_null = pd.read_csv('/content/Iris_null.csv')
irisdf_null

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,NaN,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [ ]:
irisdf_null.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  148 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  148 non-null    float64
 4   PetalWidthCm   149 non-null    float64
 5   Species        148 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [ ]:
irisdf_null.isnull().sum()

Id               0
SepalLengthCm    2
SepalWidthCm     0
PetalLengthCm    2
PetalWidthCm     1
Species          2
dtype: int64

In [ ]:
clear_irisdf = irisdf_null.dropna()
clear_irisdf

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
144,145,6.7,3.3,5.7,2.5,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [ ]:
clear_irisdf.info()

<class 'pandas.core.frame.DataFrame'>
Index: 143 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             143 non-null    int64
 1   SepalLengthCm  143 non-null    float64
 2   SepalWidthCm   143 non-null    float64
 3   PetalLengthCm  143 non-null    float64
 4   PetalWidthCm   143 non-null    float64
 5   Species        143 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.8+ KB

In [ ]:
irisdf_null.shape

(150, 6)

In [ ]:
irisdf_null['PetalLengthCm'].mean()

np.float64(3.7648648648648653)

In [ ]:
irisdf_null['SepalLengthCm_mean'] = irisdf_null['SepalLengthCm'].fillna(
    irisdf_null['SepalLengthCm'].mean()
)

irisdf_null.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Id                  150 non-null    int64
 1   SepalLengthCm       148 non-null    float64
 2   SepalWidthCm        150 non-null    float64
 3   PetalLengthCm       148 non-null    float64
 4   PetalWidthCm        149 non-null    float64
 5   Species             148 non-null    object
 6   SepalLengthCm_mean  150 non-null    float64
dtypes: float64(5), int64(1), object(1)
memory usage: 8.3+ KB

In [ ]:
irisdf_null[irisdf_null['SepalLengthCm'].isnull()]

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,SepalLengthCm_mean
22,23,NaN,3.6,1.0,0.2,Iris-setosa,5.847973
115,116,NaN,3.2,5.3,2.3,Iris-virginica,5.847973

In [ ]:
import pandas as pd
irisdf_null = pd.read_csv('/content/Iris_null.csv')
irisdf_null['Species'].mode()

0    Iris-versicolor
1     Iris-virginica
Name: Species, dtype: object

In [ ]:
df = pd.DataFrame({
    'A' : [1,None,None,4],
    'B' : [None, 2, None,5]

})
df

     A    B
0  1.0  NaN
1  NaN  2.0
2  NaN  NaN
3  4.0  5.0

In [2]:
import pandas as pd
df = pd.DataFrame({
    'A' : [1,None,None,4],
    'B' : [None, 2, None,5]
})
df.bfill()

     A    B
0  1.0  2.0
1  4.0  2.0
2  4.0  5.0
3  4.0  5.0

In [3]:
import numpy as np

In [5]:
list1 = [1,2,3]
arr1 = np.array(list1)
arr1

array([1, 2, 3])

In [7]:
arr2 = np.array(
    [
    [1,2,3],
    [4,5,6]
    ]
)
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
arr3 = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [1,2,3],
         [4,5,6]
    ]
])
arr3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [11]:
print(type(arr1))
print(type(arr2))
print(type(arr3))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>

In [13]:
arr1.ndim, arr2.ndim, arr3.ndim

(1, 2, 3)

In [14]:
arr2.shape

(2, 3)

In [15]:
arr2.size

6

In [16]:
np.sum(arr2)

np.int64(21)

In [17]:
print(np.sum(arr2,axis = 0))
print(np.sum(arr2,axis=1))

[5 7 9]
[ 6 15]

In [18]:
np.zeros(2)

array([0., 0.])

In [19]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np.full((2,3),10)

array([[10, 10, 10],
       [10, 10, 10]])

In [21]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
np.empty((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [25]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [27]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [34]:
 np.random.rand(2,3)

array([[0.48988608, 0.50602804, 0.01365553],
       [0.14912823, 0.11022034, 0.59758685]])

In [38]:
arr5 = np.random.randint(1, 20, (4,5))
arr5

array([[ 9, 13,  7, 13, 19],
       [ 6, 11,  7, 12, 12],
       [ 1, 18, 14, 19, 10],
       [ 7,  9, 10, 11,  6]])

In [39]:
arr5.flatten()

array([ 9, 13,  7, 13, 19,  6, 11,  7, 12, 12,  1, 18, 14, 19, 10,  7,  9,
       10, 11,  6])

In [40]:
a1 =np.random.rand(2,3)
a2 = np.random.rand(2,3)
print(a1)
print(a2)

[[0.80126923 0.85736377 0.90095578]
 [0.69423403 0.89362623 0.4059845 ]]
[[0.47403897 0.07622224 0.72862257]
 [0.57419362 0.64052253 0.40050668]]

In [41]:
a1.T

array([[0.80126923, 0.69423403],
       [0.85736377, 0.89362623],
       [0.90095578, 0.4059845 ]])

In [42]:
arr1

array([1, 2, 3])

In [45]:
sq = np.square(arr1)
sq

array([1, 4, 9])

In [46]:
np.subtract(a1,a2)

array([[0.32723025, 0.78114153, 0.17233322],
       [0.1200404 , 0.2531037 , 0.00547783]])

In [49]:
np.dot(a1,a2.T)

array([[1.10163975, 1.3700833 ],
       [0.69301765, 1.13361199]])

In [50]:
np.min(arr5)

np.int64(1)

In [52]:
arr1 = np.array([1,2,3])
arr1 = np.array([8,2,3])
np.sum(arr1 == arr2)

np.int64(2)